### ISSUE TITLE
Failed to build (missing node module?)

### ISSUE THREAD

**Issue by mike-code** [jandd/graylog-plugin-auth-oidc#1]
Hi. I see that your plugin might not be ready to use by broader audience, but perhaps you'll be able to help me out as I'd like to try it out.

I'm complete nodejs illiterate. Why is it needed anyway though? Is it used to create a configuration page in graylogs admin panel?

Here's output from `mvn package`

	❯ mvn package
	[INFO] Scanning for projects...
	[WARNING] The project org.graylog.plugins:graylog-plugin-auth-oidc:jar:3.1.1-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
	[INFO]
	[INFO] ------------< org.graylog.plugins:graylog-plugin-auth-oidc >------------
	[INFO] Building graylog-plugin-auth-oidc 3.1.1-SNAPSHOT
	[INFO] --------------------------------[ jar ]---------------------------------
	[INFO]
	[INFO] --- frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) @ graylog-plugin-auth-oidc ---
	[INFO] Node v10.13.0 is already installed.
	[INFO] Yarn 1.12.3 is already installed.
	[INFO]
	[INFO] --- frontend-maven-plugin:1.6:yarn (yarn install) @ graylog-plugin-auth-oidc ---
	[INFO] Running 'yarn install' in /tmp/graylog-plugin-auth-oidc
	[INFO] yarn install v1.12.3
	[INFO] [1/4] Resolving packages...
	[INFO] success Already up-to-date.
	[INFO] Done in 0.52s.
	[INFO]
	[INFO] --- frontend-maven-plugin:1.6:yarn (yarn run build) @ graylog-plugin-auth-oidc ---
	[INFO] Running 'yarn run build' in /tmp/graylog-plugin-auth-oidc
	[INFO] yarn run v1.12.3
	[INFO] $ webpack --bail
	[ERROR] Running in production mode
	[ERROR] ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin'
	[ERROR]     at factory.create (/tmp/graylog-plugin-auth-oidc/node_modules/webpack/lib/Compilation.js:925:10)
	[ERROR]     at factory (/tmp/graylog-plugin-auth-oidc/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
	[ERROR]     at resolver (/tmp/graylog-plugin-auth-oidc/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
	[ERROR]     at asyncLib.parallel (/tmp/graylog-plugin-auth-oidc/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
	[ERROR]     at /tmp/graylog-plugin-auth-oidc/node_modules/neo-async/async.js:2830:7
	[ERROR]     at /tmp/graylog-plugin-auth-oidc/node_modules/neo-async/async.js:6877:13
	[ERROR]     at normalResolver.resolve (/tmp/graylog-plugin-auth-oidc/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
	[ERROR]     at doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
	[ERROR]     at resolver.doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
	[ERROR]     at resolver.doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn42 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
	[ERROR]     at resolver.doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn3 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
	[ERROR]     at resolver.doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
	[ERROR]     at resolver.doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn43 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
	[ERROR]     at hook.callAsync (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
	[ERROR]     at _fn0 (eval at create (/tmp/graylog-plugin-auth-oidc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
	[ERROR]     at resolver.doResolve (/tmp/graylog-plugin-auth-oidc/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
	[ERROR] resolve 'fs' in '/tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin'
	[ERROR]   Parsed request is a module
	[ERROR]   using description file: /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/package.json (relative path: .)
	[ERROR]     Field 'browser' doesn't contain a valid alias configuration
	[ERROR]     resolve as module
	[ERROR]       looking for modules in /tmp/graylog2-server/graylog2-web-interface/src
	[ERROR]         using description file: /tmp/graylog2-server/graylog2-web-interface/package.json (relative path: ./src)
	[ERROR]           Field 'browser' doesn't contain a valid alias configuration
	[ERROR]           using description file: /tmp/graylog2-server/graylog2-web-interface/package.json (relative path: ./src/fs)
	[ERROR]             no extension
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/src/fs doesn't exist
	[ERROR]             .js
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/src/fs.js doesn't exist
	[ERROR]             .json
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/src/fs.json doesn't exist
	[ERROR]             .jsx
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/src/fs.jsx doesn't exist
	[ERROR]             .ts
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/src/fs.ts doesn't exist
	[ERROR]             as directory
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/src/fs doesn't exist
	[ERROR]       /tmp/graylog-plugin-auth-oidc/node_modules/node_modules doesn't exist or is not a directory
	[ERROR]       /tmp/node_modules doesn't exist or is not a directory
	[ERROR]       /node_modules doesn't exist or is not a directory
	[ERROR]       looking for modules in /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules
	[ERROR]         using description file: /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/package.json (relative path: ./node_modules)
	[ERROR]           Field 'browser' doesn't contain a valid alias configuration
	[ERROR]       looking for modules in /tmp/graylog-plugin-auth-oidc/node_modules
	[ERROR]         using description file: /tmp/graylog-plugin-auth-oidc/package.json (relative path: ./node_modules)
	[ERROR]           Field 'browser' doesn't contain a valid alias configuration
	[ERROR]           using description file: /tmp/graylog-plugin-auth-oidc/node_modules/fs/package.json (relative path: .)
	[ERROR]             no extension
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]           using description file: /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/package.json (relative path: ./node_modules/fs)
	[ERROR]             no extension
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/fs is not a file
	[ERROR]             .js
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules/fs doesn't exist
	[ERROR]             .js
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/fs.js doesn't exist
	[ERROR]             .json
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules/fs.js doesn't exist
	[ERROR]             .json
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/fs.json doesn't exist
	[ERROR]             .jsx
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules/fs.json doesn't exist
	[ERROR]             .jsx
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/fs.jsx doesn't exist
	[ERROR]             .ts
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules/fs.jsx doesn't exist
	[ERROR]             .ts
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/fs.ts doesn't exist
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules/fs.ts doesn't exist
	[ERROR]             as directory
	[ERROR]               existing directory
	[ERROR]                 use ./index.js from main in package.json
	[ERROR]                   using description file: /tmp/graylog-plugin-auth-oidc/node_modules/fs/package.json (relative path: .)
	[ERROR]                     Field 'browser' doesn't contain a valid alias configuration
	[ERROR]             as directory
	[ERROR]               /tmp/graylog-plugin-auth-oidc/node_modules/html-webpack-plugin/node_modules/fs doesn't exist
	[ERROR]                     using description file: /tmp/graylog-plugin-auth-oidc/node_modules/fs/package.json (relative path: ./index.js)
	[ERROR]                       no extension
	[ERROR]                         Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                         /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js doesn't exist
	[ERROR]                       .js
	[ERROR]                         Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                         /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js.js doesn't exist
	[ERROR]                       .json
	[ERROR]                         Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                         /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js.json doesn't exist
	[ERROR]                       .jsx
	[ERROR]                         Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                         /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js.jsx doesn't exist
	[ERROR]                       .ts
	[ERROR]                         Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                         /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js.ts doesn't exist
	[ERROR]                       as directory
	[ERROR]                         /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js doesn't exist
	[ERROR]                 using path: /tmp/graylog-plugin-auth-oidc/node_modules/fs/index
	[ERROR]                   using description file: /tmp/graylog-plugin-auth-oidc/node_modules/fs/package.json (relative path: ./index)
	[ERROR]                     no extension
	[ERROR]                       Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                       /tmp/graylog-plugin-auth-oidc/node_modules/fs/index doesn't exist
	[ERROR]                     .js
	[ERROR]                       Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                       /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.js doesn't exist
	[ERROR]                     .json
	[ERROR]                       Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                       /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.json doesn't exist
	[ERROR]                     .jsx
	[ERROR]                       Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                       /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.jsx doesn't exist
	[ERROR]                     .ts
	[ERROR]                       Field 'browser' doesn't contain a valid alias configuration
	[ERROR]                       /tmp/graylog-plugin-auth-oidc/node_modules/fs/index.ts doesn't exist
	[ERROR]       looking for modules in /tmp/graylog2-server/graylog2-web-interface/public
	[ERROR]         using description file: /tmp/graylog2-server/graylog2-web-interface/package.json (relative path: ./public)
	[ERROR]           Field 'browser' doesn't contain a valid alias configuration
	[ERROR]           using description file: /tmp/graylog2-server/graylog2-web-interface/package.json (relative path: ./public/fs)
	[ERROR]             no extension
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/public/fs doesn't exist
	[ERROR]             .js
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/public/fs.js doesn't exist
	[ERROR]             .json
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/public/fs.json doesn't exist
	[ERROR]             .jsx
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/public/fs.jsx doesn't exist
	[ERROR]             .ts
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/public/fs.ts doesn't exist
	[ERROR]             as directory
	[ERROR]               /tmp/graylog2-server/graylog2-web-interface/public/fs doesn't exist
	[ERROR]       looking for modules in /tmp/graylog-plugin-auth-oidc/src/web
	[ERROR]         using description file: /tmp/graylog-plugin-auth-oidc/package.json (relative path: ./src/web)
	[ERROR]           Field 'browser' doesn't contain a valid alias configuration
	[ERROR]           using description file: /tmp/graylog-plugin-auth-oidc/package.json (relative path: ./src/web/fs)
	[ERROR]             no extension
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/src/web/fs doesn't exist
	[ERROR]             .js
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/src/web/fs.js doesn't exist
	[ERROR]             .json
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/src/web/fs.json doesn't exist
	[ERROR]             .jsx
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/src/web/fs.jsx doesn't exist
	[ERROR]             .ts
	[ERROR]               Field 'browser' doesn't contain a valid alias configuration
	[ERROR]               /tmp/graylog-plugin-auth-oidc/src/web/fs.ts doesn't exist
	[ERROR]             as directory
	[ERROR]               /tmp/graylog-plugin-auth-oidc/src/web/fs doesn't exist
	[ERROR] error Command failed with exit code 1.
	[INFO] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
	[INFO] ------------------------------------------------------------------------
	[INFO] BUILD FAILURE
	[INFO] ------------------------------------------------------------------------
	[INFO] Total time:  21.871 s
	[INFO] Finished at: 2020-04-16T11:31:42Z
	[INFO] ------------------------------------------------------------------------
	[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (yarn run build) on project graylog-plugin-auth-oidc: Failed to run task: 'yarn run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
	[ERROR]
	[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
	[ERROR] Re-run Maven using the -X switch to enable full debug logging.
	[ERROR]
	[ERROR] For more information about the errors and possible solutions, please read the following articles:
	[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by fbettag** [comment]
i have a similar problem on OpenBSD, but i have node and yarn already installed through my package management (where this would work).

Maybe the owner of this repo could put a .jar file under github releases? :) that would ease up testing very much. thanks

**Comment by mike-code** [comment]
Not sure if this plugin is complete to be honest. I can't really see how it'd work with an external oidc provider. 

I went with official SSO plugin instead.

**Comment by jandd** [comment]
Sorry for the confusion and thanks for your interest. This repo only contains WIP code and I had no time to work on a proper implementation yet. The nodejs/yarn is needed by the admin interface and are required for the React part. There is a discussion related to the build issues https://community.graylog.org/t/compiling-graylog-from-master-fails-with-yarn-error/12254

**Comment by jandd** [comment]
I do not use Graylog anymore and will not continue work on this plugin
